provider:
  name: aws
  region: eu-west-2
  runtime: nodejs10.x
  memorySize: 128
  stage: dev

service:
  name: nest-serverless

plugins:
  - serverless-plugin-typescript
  # - serverless-plugin-optimize
  - serverless-offline

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}

package:
  individually: true # Set your packages to be built individually to have smaller packages
